# Generated by Django 5.0.7 on 2024-08-13 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDelNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50, verbose_name='notification')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('members', models.ManyToManyField(blank=True, related_name='comdelnot', to=settings.AUTH_USER_MODEL, verbose_name='user notification')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
