# Generated by Django 5.0.7 on 2024-08-14 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_communitydelnotification_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitydelnotification',
            name='is_read',
        ),
        migrations.AddField(
            model_name='communitydelnotification',
            name='readers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='notification readers'),
        ),
    ]
