# Generated by Django 5.0.7 on 2024-08-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_communitydelnotification_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydelnotification',
            name='deleter',
            field=models.CharField(blank=True, max_length=50, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='communitydelnotification',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='communitydelnotification',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='status'),
        ),
    ]
