# Generated by Django 5.0.7 on 2024-08-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_communitydelnotification_deleter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydelnotification',
            name='action',
            field=models.CharField(blank=True, max_length=50, verbose_name='type of action'),
        ),
        migrations.AlterField(
            model_name='communitydelnotification',
            name='deleter',
            field=models.CharField(blank=True, max_length=50, verbose_name='community-deleter'),
        ),
        migrations.AlterField(
            model_name='communitydelnotification',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='community-name'),
        ),
    ]
