# Generated by Django 5.0.7 on 2024-11-21 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_communitydelnotification_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='following', max_length=50, verbose_name='status')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('follower', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='whoifollow', to=settings.AUTH_USER_MODEL, verbose_name='follower')),
                ('following', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='whofollow', to=settings.AUTH_USER_MODEL, verbose_name='following')),
            ],
        ),
    ]
