# Generated by Django 5.0.7 on 2024-11-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_followingnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followingnotification',
            name='status',
            field=models.CharField(default='following', editable=False, max_length=50, verbose_name='status'),
        ),
    ]
