# Generated by Django 5.0.7 on 2024-11-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_followingnotification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydelnotification',
            name='info',
            field=models.CharField(blank=True, max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='communitydelnotification',
            name='status',
            field=models.CharField(default='community_deletion', editable=False, max_length=50, verbose_name='status'),
        ),
    ]
