# Generated by Django 5.0.7 on 2024-11-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_followingnotification_readers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitydelnotification',
            old_name='created',
            new_name='date',
        ),
    ]
