# Generated by Django 5.0.7 on 2024-11-21 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_rename_created_communitydelnotification_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='followingnotification',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='readFNotif', to=settings.AUTH_USER_MODEL, verbose_name='notification readers'),
        ),
    ]
