# Generated by Django 5.0.7 on 2024-11-21 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_alter_followingnotification_readers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followingnotification',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='followingNotif', to=settings.AUTH_USER_MODEL, verbose_name='user notification'),
        ),
    ]
