# Generated by Django 5.0.7 on 2024-11-21 23:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_followingnotification_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='followingnotification',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='followingNotif', to=settings.AUTH_USER_MODEL, verbose_name='following notif members'),
        ),
    ]
