# Generated by Django 5.0.7 on 2024-08-08 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechatapp', '0002_alter_message_user_from_alter_message_user_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Message_date')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='communitychats', to=settings.AUTH_USER_MODEL, verbose_name='From')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Community-Name')),
                ('date', models.DateField(verbose_name='created')),
                ('admins', models.ManyToManyField(blank=True, default='self.creator', related_name='leadingcommunities', to=settings.AUTH_USER_MODEL, verbose_name='admins')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('members', models.ManyToManyField(related_name='communities', to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('chats', models.ManyToManyField(blank=True, to='livechatapp.communitychat', verbose_name='')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
