# Generated by Django 5.0.7 on 2024-08-08 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechatapp', '0003_communitychat_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='chats',
            field=models.ManyToManyField(blank=True, to='livechatapp.communitychat', verbose_name='Chats'),
        ),
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='communities', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
    ]
