# Generated by Django 5.0.7 on 2024-08-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechatapp', '0004_alter_community_chats_alter_community_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ('-chats__date',)},
        ),
        migrations.AlterField(
            model_name='community',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='created'),
        ),
    ]
