# Generated by Django 5.0.7 on 2024-08-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechatapp', '0005_alter_community_options_alter_community_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='chats',
            field=models.ManyToManyField(blank=True, related_name='chat_community', to='livechatapp.communitychat', verbose_name='Chats'),
        ),
    ]
