# Generated by Django 5.0.7 on 2024-08-11 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechatapp', '0007_alter_community_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='only_admin_chat',
            field=models.BooleanField(default=False, verbose_name='Allow Chat'),
        ),
        migrations.AlterField(
            model_name='community',
            name='admins',
            field=models.ManyToManyField(blank=True, default='Creator', related_name='leadingcommunities', to=settings.AUTH_USER_MODEL, verbose_name='admins'),
        ),
    ]
