# Generated by Django 5.0.7 on 2024-08-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechatapp', '0008_community_only_admin_chat_alter_community_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='only_admin_chat',
            field=models.BooleanField(default=True, verbose_name='Allow Chat'),
        ),
    ]
