# Generated by Django 5.0.7 on 2024-11-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechatapp', '0014_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitychat',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
    ]
