# Generated by Django 5.0.7 on 2024-11-19 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechatapp', '0015_communitychat_read_message_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitychat',
            name='read',
        ),
        migrations.AddField(
            model_name='communitychat',
            name='readers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='readers'),
        ),
    ]
