# Generated by Django 5.0.7 on 2024-11-19 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechatapp', '0016_remove_communitychat_read_communitychat_readers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitychat',
            name='readers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='readers'),
        ),
    ]
