# Generated by Django 5.0.7 on 2024-11-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechatapp', '0017_alter_communitychat_readers'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitychat',
            name='delete_for_me',
            field=models.BooleanField(default=False, verbose_name='delete for me'),
        ),
        migrations.AddField(
            model_name='message',
            name='delete_for_me',
            field=models.BooleanField(default=False, verbose_name='delete for me'),
        ),
    ]
