# Generated by Django 5.0.7 on 2024-11-22 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechatapp', '0018_communitychat_delete_for_me_message_delete_for_me'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='delete_for_me',
        ),
        migrations.AddField(
            model_name='message',
            name='delete_for_me',
            field=models.ManyToManyField(default=[models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fromme', to=settings.AUTH_USER_MODEL, verbose_name='From'), models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tome', to=settings.AUTH_USER_MODEL, verbose_name='To')], to=settings.AUTH_USER_MODEL, verbose_name='ownership'),
        ),
    ]
