# Generated by Django 5.0.7 on 2024-11-22 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechatapp', '0021_alter_message_delete_for_me'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitychat',
            name='delete_for_me',
        ),
        migrations.AddField(
            model_name='communitychat',
            name='delete_for_me',
            field=models.ManyToManyField(related_name='cdelforme', to=settings.AUTH_USER_MODEL, verbose_name='delete for me'),
        ),
    ]
