# Generated by Django 5.0.7 on 2024-11-22 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechatapp', '0022_remove_communitychat_delete_for_me_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitychat',
            name='delete_for_me',
            field=models.ManyToManyField(blank=True, related_name='cdelforme', to=settings.AUTH_USER_MODEL, verbose_name='delete for me'),
        ),
        migrations.AlterField(
            model_name='message',
            name='delete_for_me',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='delete for me'),
        ),
    ]
