# Generated by Django 5.0.7 on 2024-11-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechatapp', '0024_alter_communitychat_date_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='only_admin_chat',
            field=models.BooleanField(default=False, verbose_name='Allow Chat'),
        ),
    ]
