# Generated by Django 5.0.7 on 2024-08-01 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followings', to=settings.AUTH_USER_MODEL, verbose_name='Followers'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
