# Generated by Django 5.0.7 on 2024-09-01 17:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.FileField(blank=True, default='media/default.jpg', null=True, upload_to=accounts.models.set_picture, verbose_name='profile pic'),
        ),
    ]
