# Generated by Django 5.0.7 on 2024-11-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forget_password_otp',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
