# Generated by Django 5.0.7 on 2024-08-01 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300, verbose_name='post')),
                ('views', models.IntegerField(blank=True, default=0, verbose_name='Views')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='post-date')),
                ('likes', models.ManyToManyField(blank=True, related_name='userpostlikes', to=settings.AUTH_USER_MODEL, verbose_name='post likes')),
                ('reposts', models.ManyToManyField(blank=True, related_name='userpostreposts', to=settings.AUTH_USER_MODEL, verbose_name='post reposts')),
                ('shares', models.ManyToManyField(blank=True, related_name='userpostshares', to=settings.AUTH_USER_MODEL, verbose_name='post shares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userposts', to=settings.AUTH_USER_MODEL, verbose_name='post user')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300, verbose_name='comment')),
                ('views', models.IntegerField(blank=True, default=0, verbose_name='Views')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='comment-date')),
                ('likes', models.ManyToManyField(blank=True, related_name='usercommentlikes', to=settings.AUTH_USER_MODEL, verbose_name='comment likes')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comment', verbose_name='Parent-comment')),
                ('reposts', models.ManyToManyField(blank=True, related_name='usercommentreposts', to=settings.AUTH_USER_MODEL, verbose_name='comment reposts')),
                ('shares', models.ManyToManyField(blank=True, related_name='usercommentshares', to=settings.AUTH_USER_MODEL, verbose_name='comment shares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercomments', to=settings.AUTH_USER_MODEL, verbose_name='comment user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcomments', to='posts.post', verbose_name='comment post')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
