# Generated by Django 5.0.7 on 2024-08-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='comment'),
        ),
    ]
